#
#	Command & Conquer Red Alert(tm)
#	Copyright 2025 Electronic Arts Inc.
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

#***************************************************************************
#**     C O N F I D E N T I A L --- W E S T W O O D   S T U D I O S       **
#***************************************************************************
#*                                                                         *
#*                 Project Name : Westwood Library .LIB makefile	   		*
#*                                                                         *
#*                    File Name : MAKEFILE                                 *
#*                                                                         *
#*                   Programmer : Julio R. Jerez			   					*
#*                                                                         *
#*                   Start Date : Jan 26, 1995                           	*
#*                                                                         *
#*                                                                         *
#*-------------------------------------------------------------------------*
#*                                                                         *
#* Required environment variables:					   								*
#* WIN32LIB		= your root WWFLAT path					   							*
#* WIN32VCS		= root directory for wwlib version control archive	   		*
#* COMPILER		= your Watcom installation path				   					*
#*									   															*
#* Required changes to makefile:					   									*
#* LIBS		= list of all component libraries			   						*
#*									   															*
#* NOTE: For this makefile to work, each library directory MUST have the   *
#*	same name as its library.					   										*
#*									   															*
#* "make install" installs the library on your drive			   				*
#* "make update" updates all source files in your slice			   			*
#*									   															*
#*	To install or update just one library you may type:		   				*
#*		 "make -DLIBS=library.lib install"				   								*
#*									   															*
#***************************************************************************

#.SILENT
#.OPTIMIZE
#.ERASE

!ifndef %WIN32LIB
WIN32LIB=.
!else
WIN32LIB=$(%WIN32LIB)
!endif


#===========================================================================
# User-defined section: list each library in this macro
#	NOTE: These are some order dependencies:
#	1. The directory LIBRARY must always be made first.
#	2. The directory VIDEO must be made before the SYSTEM directory.
#===========================================================================
LIB_NAME = WIN32LIB
LIB_DIR  = $(WIN32LIB)\LIB

#---------------------------------------------------------------------------
# LIBS macro: a list of all component libraries
#	"make LIBS=xxxx.lib [target]" makes/installs/updates only that library
#---------------------------------------------------------------------------

LIBS = 			&
					AUDIO.LIB		&
					DIPTHONG.LIB	&
					DRAWBUFF.LIB	&
					FONT.LIB    	&
					IFF.LIB	    	&
					KEYBOARD.LIB	&
					MEM.LIB	    	&
					LIBRARY.LIB    	&
					MONO.LIB    	&
					PALETTE.LIB 	&
					SHAPE.LIB		&
					TILE.LIB 		&
					TIMER.LIB 		&
					WW_WIN.LIB 		&
					WSA.LIB	  		&
					PROFILE.LIB    &
					PLAYCD.LIB	&
					WINCOMM.LIB

LIB_INSTALL =	&
					AUDIO.INS		&
					DIPTHONG.INS	&
					DRAWBUFF.INS	&
					FONT.INS    	&
					IFF.INS	    	&
					KEYBOARD.INS	&
					MEM.INS	    	&
					LIBRARY.INS    	&
					MONO.INS    	&
					PALETTE.INS 	&
					RAWFILE.INS		&
					SHAPE.INS		&
					TILE.INS 		&
					TIMER.INS 		&
					WW_WIN.INS 		&
					WSA.INS	  		&
					PROFILE.INS		&
					PLAYCD.INS		&
					WINCOMM.INS

LIB_UPDATE =	&
					AUDIO.UPD		&
					DIPTHONG.UPD	&
					DRAWBUFF.UPD	&
					FONT.UPD    	&
					IFF.UPD	    	&
					KEYBOARD.UPD	&
					MEM.UPD	    	&
					LIBRARY.UPD    	&
					MONO.UPD    	&
					PALETTE.UPD 	&
					RAWFILE.UPD		&
					SHAPE.UPD		&
					TILE.UPD 		&
					TIMER.UPD 		&
					WW_WIN.UPD 		&
					WSA.UPD	  		&
					PROFILE.UPD		&
					PLAYCD.UPD		&
					WINCOMM.UPD

LIB_CLEAN =	&
					AUDIO.CLN		&
					DIPTHONG.CLN	&
					DRAWBUFF.CLN	&
					FONT.CLN    	&
					IFF.CLN	    	&
					KEYBOARD.CLN	&
					MEM.CLN	    	&
					LIBRARY.CLN    	&
					MONO.CLN    	&
					PALETTE.CLN 	&
					RAWFILE.CLN		&
					SHAPE.CLN		&
					TILE.CLN 		&
					TIMER.CLN 		&
					WW_WIN.CLN 		&
					WSA.CLN	  		&
					PROFILE.CLN		&
					PLAYCD.CLN		&
					WINCOMM.CLN

MODULES = &
					AUDIO			&
					DIPTHONG		&
					DRAWBUFF		&
					FONT			&
					IFF				&
					KEYBOARD		&
					MEM				&
					LIBRARY			&
					MONO			&
					PALETTE			&
					RAWFILE			&
					SHAPE			&
					TILE			&
					TIMER			&
					WW_WIN			&
					WSA				&
					PROFILE			&
					PLAYCD			&
					WINCOMM			&


#===========================================================================
# Pre-defined section: there should be little need to modify this section.
#===========================================================================
#---------------------------------------------------------------------------
# Path macros: one path for each file type.
#	These paths are used to tell make where to find/put each file type.
#---------------------------------------------------------------------------
.lib: $(WIN32LIB)\LIB


#---------------------------------------------------------------------------
# Tools/commands
# LIB_CMD:	library command
# LIB_CFG:	library configuration file
# VCS_UPDATE:	version control update command; this command should update
# 		all relevant files in a given directory with read-only
#		copies from the archive
#---------------------------------------------------------------------------
!include $(WIN32LIB)\PROJECT.CFG
LIB_CMD = $(%WATCOM)\binnt\wlib
VCS_UPDATE = update

#---------------------------------------------------------------------------
# Ensure build directories exist before any compilation
#---------------------------------------------------------------------------
.BEFORE
	@echo.
	@echo Creating build directories.
	@if not exist "$(WIN32LIB)\INCLUDE" md "$(WIN32LIB)\INCLUDE" 2>nul
	@if not exist "$(WIN32LIB)\LIB" md "$(WIN32LIB)\LIB" 2>nul
	@for %%M in ($(MODULES)) do @if not exist "$(WIN32LIB)\%%M\OBJ" md "$(WIN32LIB)\%%M\OBJ" 2>nul

#---------------------------------------------------------------------------
# Default target
#---------------------------------------------------------------------------
all:	$(LIB_DIR)\$(LIB_NAME).lib .SYMBOLIC

#---------------------------------------------------------------------------
# "make clean" cleans all source files in your slice
#---------------------------------------------------------------------------
clean: $(LIB_CLEAN) .SYMBOLIC
	echo.
	echo Cleaning library.

#---------------------------------------------------------------------------
# This target cleans all library directories
#	This is a dependency for 'clean'
#---------------------------------------------------------------------------
$(LIB_CLEAN): .SYMBOLIC
	@echo.
	@echo Cleaning up '$^&' files!
	@dir /b /a-d "$(WIN32LIB)\$^&\OBJ\*.OBJ" >nul 2>&1 && del "$(WIN32LIB)\$^&\OBJ\*.OBJ" || ver >nul
	@dir /b /a-d "$(WIN32LIB)\$^&\OBJ\*.ERR" >nul 2>&1 && del "$(WIN32LIB)\$^&\OBJ\*.ERR" || ver >nul
	@dir /b /a-d "$(WIN32LIB)\LIB\$^&.LIB" >nul 2>&1 && del "$(WIN32LIB)\LIB\$^&.LIB" || ver >nul
	@dir /b /a-d "$(WIN32LIB)\$^&\*.LIB" >nul 2>&1 && del "$(WIN32LIB)\$^&\*.LIB" || ver >nul
	@dir /b /a-d "$(WIN32LIB)\$^&\OBJECTS.LBC" >nul 2>&1 && del "$(WIN32LIB)\$^&\OBJECTS.LBC" 2>nul || ver >nul


#---------------------------------------------------------------------------
# Build the library
# The original library is deleted by the librarian
# Lib objects & -+ commands are constructed by substituting within the
# $^@ macro (which expands to all target dependents, separated with
# spaces)
# Tlib's cfg file is not invoked as a response file.
# All headers & source files are copied into WIN32LIB\SRCDEBUG, for debugging
#---------------------------------------------------------------------------
$(LIB_DIR)\$(LIB_NAME).lib: $(LIBS) LIBS.LBC
	$(LIB_CMD) $(LIB_CFG) $^@ @LIBS.LBC


#---------------------------------------------------------------------------
# This construct tells make how to make all component libraries
# The commands get executed for every item in the macro.
#	The macro $: extracts only the directory name from the macro item.
#---------------------------------------------------------------------------
$(LIBS):
	echo.
	echo Making '$^&'...
	cd $^&
	wmake
	cd ..

#---------------------------------------------------------------------------
# Libs is librarian response file that is only genarated if any of the 
# sublibrary in the golbal variable LIBS was updated.
#---------------------------------------------------------------------------
libs.lbc : $(LIBS)
	   %create $^@
	   for %index in ($(LIBS)) do %append $^@ +$(LIB_DIR)\%index


#---------------------------------------------------------------------------
# "make install" installs the library on your drive
#---------------------------------------------------------------------------
install:  install_dirs $(LIB_INSTALL) .SYMBOLIC
	echo.
	echo Compiling library...
	wmake
	echo Library installation complete.

#---------------------------------------------------------------------------
# At installation time, this target makes all non-library directories
#	This is a dependency for 'install'
#---------------------------------------------------------------------------
install_dirs: .SYMBOLIC
	echo Making directories...
	mkdir example
	mkdir include
	mkdir lib   
	mkdir srcdebug
	mkdir tools
	cd tools  
	copy $(%WWVCS)\tools\vcs.cfg
	$(VCS_UPDATE) 
	cd..   
	copy $(%WWVCS)\vcs.cfg
	$(VCS_UPDATE) 
	cd example 
	copy $(%WWVCS)\example\vcs.cfg 
	$(VCS_UPDATE) 
	cd ..


#---------------------------------------------------------------------------
# This target installs all library directories
#	This is a dependency for 'install'
#---------------------------------------------------------------------------
$(LIB_INSTALL):	.SYMBOLIC
	echo Installing $^&...
	md $^&
	cd $^&
	copy $(%WWVCS)\$^&\vcs.cfg 
	$(VCS_UPDATE) 
	copy *.h $(WIN32LIB)\INCLUDE
	copy *.inc $(WIN32LIB)\INCLUDE
	cd ..


#---------------------------------------------------------------------------
# "make update" updates all source files in your slice
#---------------------------------------------------------------------------
update: $(LIB_UPDATE) .SYMBOLIC
	echo.
	echo Library updated.


#---------------------------------------------------------------------------
# This target updates all library directories
#	This is a dependency for 'updates'
#---------------------------------------------------------------------------
$(LIB_UPDATE): .SYMBOLIC
	@echo.
	@echo Updating '$^&' headers files in '$(WIN32LIB)\INCLUDE'!
	@if not exist "$(WIN32LIB)\INCLUDE\" md "$(WIN32LIB)\INCLUDE\" 2>nul
#	cd $^&
#	$(VCS_UPDATE)
	@dir /b /a-d "$(WIN32LIB)\$^&\*.h" >nul 2>&1 && xcopy "$(WIN32LIB)\$^&\*.h" "$(WIN32LIB)\INCLUDE\" /Y /F /R /I || ver >nul
	@dir /b /a-d "$(WIN32LIB)\$^&\*.inc" >nul 2>&1 && xcopy "$(WIN32LIB)\$^&\*.inc" "$(WIN32LIB)\INCLUDE\" /Y /F /R /I || ver >nul
	@dir /b /a-d "$(WIN32LIB)\$^&\*.i" >nul 2>&1 && xcopy "$(WIN32LIB)\$^&\*.i" "$(WIN32LIB)\INCLUDE\" /Y /F /R /I || ver >nul
#	cd ..
