#
#	Command & Conquer Red Alert(tm)
#	Copyright 2025 Electronic Arts Inc.
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

#* $Header$
#***********************************************************************************************
#***              C O N F I D E N T I A L  ---  W E S T W O O D  S T U D I O S               ***
#***********************************************************************************************
#*                                                                                             *
#*                 Project Name : Command & Conquer                                            *
#*                                                                                             *
#*                    File Name : MAKEFILE                                                     *
#*                                                                                             *
#*                   Programmer : Joe L. Bostic                                                *
#*                                                                                             *
#*                   Start Date : 03/02/95                                                     *
#*                                                                                             *
#*                  Last Update : March 2, 1995 [JLB]                                          *
#*                                                                                             *
#*---------------------------------------------------------------------------------------------*
#* - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - *

.SILENT
.OPTIMIZE
.ERASE

#---------------------------------------------------------------------------
# Working values depending on what target executable will be created.
#---------------------------------------------------------------------------

!ifdef GERMAN
LANGUAGE=GERMAN
!else
!ifdef FRENCH
LANGUAGE=FRENCH
!else
LANGUAGE=ENGLISH
!endif
!endif

!ifdef RELEASE_VERSION
BUILDVERSION=RELEASE_VERSION
RUN_NAME=RA95
!else
!ifdef PLAYTEST_VERSION
BUILDVERSION=PLAYTEST_VERSION
RUN_NAME=RA95_PLAYTEST
!else
BUILDVERSION=INTERNAL_VERSION
RUN_NAME=RA95_INTERNAL
!endif
!endif

OBJ_ROOT=OBJ

!ifdef WIN32
WWOBJ_COMMON=$(OBJ_ROOT)\WIN32
LINKFILE=WIN95.LNK
CC=$(%WATCOM)\binnt\wpp386
LIB=$(%WATCOM)\binnt\wlib
!else
WWOBJ_COMMON=$(OBJ_ROOT)\DOS
LINKFILE=CONQUER.LNK
CC=$(%WATCOM)\binnt\wpp386
LIB=$(%WATCOM)\binnt\wlib
!endif

WWLIB=$(%WWLIB)
TASM=$(%TASM)
WWVQ=$(%WWVQ)
WWOBJ=$(WWOBJ_COMMON)\$(LANGUAGE)

WWRUN=$(%PRJ_ROOT)\RUN\$(LANGUAGE)

# The CnCNet private build is a separate ENGLISH-based pass. Redirect both
# the intermediate object dir and the staged output to a CnCNet-specific folder
# so it does not overwrite the plain ENGLISH build (RUN\ENGLISH\). Output lands
# in RUN\CNCNET\ instead of RUN\<LANGUAGE>\.
!ifdef CNCNET
WWOBJ=$(WWOBJ_COMMON)\CNCNET
WWRUN=$(%PRJ_ROOT)\RUN\CNCNET
!endif


#---------------------------------------------------------------------------
# Path macros: one path for each file type.
#  These paths are used to tell make where to find/put each file type.
#---------------------------------------------------------------------------
.asm:  .
.c:    .

# When building the private CnCNet variant, also search CNCNET_DIR for .cpp
# sources. Path specifiers must live here (Watcom wmake rejects them elsewhere
# with "Ignoring out of place Path Specifier"), and multiple directories must be
# SEMICOLON-separated -- a space would make wmake read CNCNET_DIR's drive-letter
# colon (e.g. X:\...) as a second path specifier and error.
!ifdef CNCNET
.cpp:  .;$(%CNCNET_DIR)
!else
.cpp:  .
!endif

.h:    .
.obj:  $(WWOBJ)
.lib:  $(WWLIB)\LIB
.exe:  $(WWRUN)


#===========================================================================
# Compiler and assembler flags.
#===========================================================================
!ifdef WIN32
CC_CFG = /d0                            # No debugging information	( else use /d1 )
CC_CFG += /DWIN32=1
CC_CFG += /D_WIN32
CC_CFG += /DWOLAPI_INTEGRATION
CC_CFG += /DWINSOCK_IPX
CC_CFG += /D$(LANGUAGE)=1
CC_CFG += /i=$(%DXSDK)\INC
CC_CFG += /i=$(%WATCOM)\H\NT                # NT include directory.
CC_CFG += /i=$(%WATCOM)\H                   # Normal Watcom include directory.
CC_CFG += /i=$(WWLIB)\INCLUDE          # Normal library include directory.
CC_CFG += /i=$(WWVQ)\INCLUDE           # Includes player (VQ) directory.
CC_CFG += /bt=NT
CC_CFG += /otxan
CC_CFG += /5r                           # Pentium optimized register calling conventions.
!else
CC_CFG = /d1                            # Partial debug (line numbers only)
CC_CFG += /i=$(%WATCOM)\H                   # Normal Watcom include directory.
CC_CFG += /i=$(WWLIB)\INCLUDE          # Normal library include directory.
CC_CFG += /i=$(WWVQ)\INCLUDE              # Includes player (VQ) directory.
CC_CFG += /DDOS4G                       # Must be defined for Greenleaf
CC_CFG += /5s                           # Pentium optimized stack calling conventions.
CC_CFG += /DGF_WATCOM_S                 # Must be defined for Greenleaf with /3s
CC_CFG += /bt=DOS
!endif

CC_CFG += /D$(LANGUAGE)=1
CC_CFG += /D$(BUILDVERSION)=1

CC_CFG += /i=$(%GCL510)\H                # Includes Greenleaf headers.
CC_CFG += /of+                          # Generate traceable stack frames.
CC_CFG += /zp1                          # Pack structures on byte boundary.
CC_CFG += /s                            # Remove stack check calls.
CC_CFG += /j                            # char is now signed.
CC_CFG += /fh=$(WWOBJ)\CONQUER.PCH      # Use precompiled headers.
CC_CFG += /fhq
CC_CFG += /we                           # Treat all warnings as errors.
CC_CFG += /w8                           # Most warnings enabled.
CC_CFG += /ri                           # char and shorts are returned as int.
CC_CFG += /zq                           # Operate quietly.

ASM_CFG = /i$(WWLIB)\INCLUDE           # Include directory.
ASM_CFG += /zd                          # Debugging information line numbers.
ASM_CFG += /t                           # Quiet operation.
ASM_CFG += /m                           # Allow multiple passes.
ASM_CFG += /w+                          # Enable maximum warnings.
ASM_CFG += /jJUMPS                      # Enable jump optimizations.
ASM_CFG += /ml                          # Case sensitivity on code.


#---------------------------------------------------------------------------
# Implicit rules
# Compiler:
# 	($< = full dependent with path)
# Assembler:
# 	output obj's are constructed from .obj: & the $& macro
# 	($< = full dependent with path)
# 	tasm's cfg file is not invoked as a response file.
#---------------------------------------------------------------------------

.c.obj: .AUTODEPEND
	echo.
	echo Compiling $<
	*$(CC) $(CC_CFG) -fo$(WWOBJ)\$^. $<

.cpp.obj: .AUTODEPEND
	echo.
	echo Compiling $<
	*$(CC) $(CC_CFG) -fo$(WWOBJ)\$^. $<

.asm.obj:
	echo.
	echo Assembling $<
	$(%MSDOS) tasm $(ASM_CFG) $<, $(WWOBJ)\$^.

#---------------------------------------------------------------------------
# Object modules.
#---------------------------------------------------------------------------
OBJECTS = &
	AADATA.OBJ &
	ABSTRACT.OBJ &
	ADATA.OBJ &
	AIRCRAFT.OBJ &
	ANIM.OBJ &
	AUDIO.OBJ &
	BAR.OBJ &
	BASE.OBJ &
	BBDATA.OBJ &
	BDATA.OBJ &
	BUILDING.OBJ &
	BULLET.OBJ &
	CARGO.OBJ &
	CARRY.OBJ &
	CCFILE.OBJ &
	CCINI.OBJ &
	CCPTR.OBJ &
	CDATA.OBJ &
	CELL.OBJ &
	CHECKBOX.OBJ &
	CHEKLIST.OBJ &
	COLRLIST.OBJ &
	COMBAT.OBJ &
	COMBUF.OBJ &
	CONNECT.OBJ &
	CONQUER.OBJ &
	CONST.OBJ &
	CONTROL.OBJ &
	COORD.OBJ &
	CRATE.OBJ &
	CREDITS.OBJ &
	CREW.OBJ &
	DEBUG.OBJ &
	DIAL8.OBJ &
	DIALOG.OBJ &
	DISPLAY.OBJ &
	DOOR.OBJ &
	DRIVE.OBJ &
	DROP.OBJ &
	DYNAVEC.OBJ &
	EDIT.OBJ &
	EGOS.OBJ &
	ENDING.OBJ &
	EVENT.OBJ &
	EXPAND.OBJ &
	FACE.OBJ &
	FACING.OBJ &
	FACTORY.OBJ &
	FINDPATH.OBJ &
	FLASHER.OBJ &
	FLY.OBJ &
	FOOT.OBJ &
	FUSE.OBJ &
	GADGET.OBJ &
	GAMEDLG.OBJ &
	GAUGE.OBJ &
	GLOBALS.OBJ &
	GOPTIONS.OBJ &
	GSCREEN.OBJ &
	HDATA.OBJ &
	HEAP.OBJ &
	HELP.OBJ &
	HOUSE.OBJ &
	IDATA.OBJ &
	INFANTRY.OBJ &
	INI.OBJ &
	INIT.OBJ &
	INTRO.OBJ &
	IOMAP.OBJ &
	IOOBJ.OBJ &
	IPX.OBJ &
	IPXADDR.OBJ &
	IPXCONN.OBJ &
	IPXGCONN.OBJ &
	IPXMGR.OBJ &
	IPXPROT.OBJ &
	JSHELL.OBJ &
	LAYER.OBJ &
	LINK.OBJ &
	LIST.OBJ &
	LOADDLG.OBJ &
	LOGIC.OBJ &
	MAP.OBJ &
	MAPEDDLG.OBJ &
	MAPEDIT.OBJ &
	MAPEDPLC.OBJ &
	MAPEDTM.OBJ &
	MAPSEL.OBJ &
	MENUS.OBJ &
	MISSION.OBJ &
	MOUSE.OBJ &
	MPLAYER.OBJ &
	MSGBOX.OBJ &
	MSGLIST.OBJ &
	NETDLG.OBJ &
	NULLCONN.OBJ &
	NULLDLG.OBJ &
	NULLMGR.OBJ &
	OBJECT.OBJ &
	ODATA.OBJ &
	OPTIONS.OBJ &
	OVERLAY.OBJ &
	POWER.OBJ &
	PROFILE.OBJ &
	QUEUE.OBJ &
	RADAR.OBJ &
	RADIO.OBJ &
	REINF.OBJ &
	RULES.OBJ &
	SAVELOAD.OBJ &
	SCENARIO.OBJ &
	SCORE.OBJ &
	SCROLL.OBJ &
	SDATA.OBJ &
	SESSION.OBJ &
	SHAPEBTN.OBJ &
	SIDEBAR.OBJ &
	SLIDER.OBJ &
	SMUDGE.OBJ &
	SOUNDDLG.OBJ &
	SPECIAL.OBJ &
	STARTUP.OBJ &
	STATBTN.OBJ &
	SUPER.OBJ &
	TAB.OBJ &
	TACTION.OBJ &
	TARGET.OBJ &
	TDATA.OBJ &
	TEAM.OBJ &
	TEAMTYPE.OBJ &
	TECHNO.OBJ &
	TEMPLATE.OBJ &
	TERRAIN.OBJ &
	TEVENT.OBJ &
	TEXTBTN.OBJ &
	THEME.OBJ &
	TOGGLE.OBJ &
	TRACKER.OBJ &
	TRIGGER.OBJ &
	TRIGTYPE.OBJ &
	TXTLABEL.OBJ &
	UDATA.OBJ &
	UNIT.OBJ &
	UTRACKER.OBJ &
	VDATA.OBJ &
	VECTOR.OBJ &
	VERSION.OBJ &
	VESSEL.OBJ &
	VISUDLG.OBJ &
	VORTEX.OBJ &
	WARHEAD.OBJ &
	WEAPON.OBJ &
	MCIMOVIE.OBJ &
	MCI.OBJ &
	MPGSET.OBJ &
	ICONLIST.OBJ &
	WOL_MAIN.OBJ &
	WOL_CHAT.OBJ &
	RAWOLAPI.OBJ &
	WOLAPIOB.OBJ &
	W95TRACE.OBJ &
	COMINIT.OBJ &
	WOL_LOGN.OBJ &
	WOLEDIT.OBJ &
	PASSEDIT.OBJ &
	SEDITDLG.OBJ &
	DIBFILE.OBJ &
	DIBUTIL.OBJ &
	WOL_GSUP.OBJ &
	UDPADDR.OBJ &
	WSPROTO.OBJ &
	WSPUDP.OBJ &
	WSPIPX.OBJ &
	_WSPROTO.OBJ &
	TOOLTIP.OBJ &
	WOL_OPT.OBJ &
	WOL_CGAM.OBJ &
	BIGCHECK.OBJ &
	WOL_DNLD.OBJ &
	WOLSTRNG.OBJ


# Files that are candidates for library submission,
# since they depend on the westwood library to a great
# degree
LIBFILES = &
	ROTBMP.OBJ &
	SPRITE.OBJ &

# Self contained technology modules
TECHFILES = &
	LZO1X_C.OBJ &
	LZO1X_D.OBJ &
	LZOPIPE.OBJ &
	LZOSTRAW.OBJ &
	LZW.OBJ &
	LZWPIPE.OBJ &
	LZWSTRAW.OBJ &
	BUFF.OBJ &
	BENCH.OBJ &
	RECT.OBJ &
	MPU.OBJ &
	READLINE.OBJ &
	PKPIPE.OBJ &
	PKSTRAW.OBJ &
	XSTRAW.OBJ &
	XPIPE.OBJ &
	RNDSTRAW.OBJ &
	PK.OBJ &
	BLWSTRAW.OBJ &
	STRAW.OBJ &
	B64STRAW.OBJ &
	LCWSTRAW.OBJ &
	CRCSTRAW.OBJ &
	SHASTRAW.OBJ &
	RAMFILE.OBJ &
	INI.OBJ &
	LCWPIPE.OBJ &
	LCWCOMP.OBJ &
	LCW.OBJ &
	CRCPIPE.OBJ &
	SHAPIPE.OBJ &
	PIPE.OBJ &
	BLOWPIPE.OBJ &
	B64PIPE.OBJ &
	BASE64.OBJ &
	FIXED.OBJ &
	MIXFILE.OBJ &
	CDFILE.OBJ &
	BFIOFILE.OBJ &
	RAWFILE.OBJ &
	MP.OBJ &
	INT.OBJ &
	MONOC.OBJ &
	RANDOM.OBJ &
	RGB.OBJ &
	HSV.OBJ &
	PALETTE.OBJ &
	BLOWFISH.OBJ &
	SHA.OBJ &
	CRC.OBJ &
	SENDFILE.OBJ

!ifdef WIN32
OBJECTS += 2KEYFBUF.OBJ &
	CPUID.OBJ &
	GETCPU.OBJ &
	INTERPAL.OBJ &
	WINASM.OBJ &
	WINSTUB.OBJ &
	2TXTPRNT.OBJ &
	WRITEPCX.OBJ &
	IPX95.OBJ &
	2KEYFRAM.OBJ &
	TCPIP.OBJ &
	INTERNET.OBJ &
	DDE.OBJ &
	CCDDE.OBJ &
	STATS.OBJ &
	PACKET.OBJ &
	KEY.OBJ &
	FIELD.OBJ

!else
OBJECTS += KEYFBUFF.OBJ &
	TXTPRNT.OBJ &
	KEYFRAME.OBJ
!endif

#---------------------------------------------------------------------------
# Pull in optional private CnCNet sources.
#
# Only wired in when the build is invoked with CNCNET=1. The source
# location is resolved by MAKE.BAT / MAKE_CNCNET.BAT into the CNCNET_DIR env var
# -- either a separate local clone (.env -> CNCNET_RED_ALERT_PRIVATE_REPO) or the
# in-tree CODE\CNCNET checkout that CI uses. A public clone without either still
# builds (CNCNET is simply not defined).
#
# The fragment appends its object names to OBJECTS, so the private sources
# compile and link with the rest of the game (one link, shared include paths) --
# there is no separate library.
#---------------------------------------------------------------------------
!ifdef CNCNET
CC_CFG += /i=.                    # let CnCNet sources reach game headers (CODE\)
CC_CFG += /i=$(%CNCNET_DIR)       # let game sources reach CNCNET headers (CNCNET.H)
!include $(%CNCNET_DIR)\MAKEFILE
!endif

!ifdef WIN32
PROJ_LIBS = &
	WIN32LIB.LIB

!else
PROJ_LIBS = &
	WWFLAT32.LIB
!endif

VQ_LIBS = &
	VQA32WP.LIB &
	VQM32WP.LIB

GCL_LIBS = &
	GCLFR3S.LIB

MEMCHECK_LIBS = &
	MCA3S.LIB

############################################################################
# Pre-compilation process. Move old files to backup directory.
.BEFORE
#	-if exist *.bak move *.bak bak
#	-if exist $(WWOBJ)\*.pch del $(WWOBJ)\*.pch
	@echo.
	@echo Creating build directories.
	@if not exist "$(WWRUN)" md "$(WWRUN)" 2>nul
	@if not exist "$(WWOBJ)" md "$(WWOBJ)" 2>nul
# Confirm the private CnCNet fragment was pulled in (banner defined there).
!ifdef CNCNET
	@echo.
	@echo $(CNCNET_FRAGMENT_BANNER)
!endif

# After make has completed.
.AFTER

# If there is an abnormal termination in make process (e.g., error in compile).
.ERROR


############################################################################
# Clean target
clean: .SYMBOLIC
	@echo.
	@echo Cleaning up '$^&' files!
    @dir /b /a-d "*.obj" >nul 2>&1 && del "*.obj" || ver >nul
    @dir /b /a-d "*.exe" >nul 2>&1 && del "*.exe" || ver >nul
    @dir /b /a-d "*.lib" >nul 2>&1 && del "*.lib" || ver >nul
    @dir /b /a-d "*.dll" >nul 2>&1 && del "*.dll" || ver >nul
    @dir /b /a-d "*.map" >nul 2>&1 && del "*.map" || ver >nul
    @dir /b /a-d "*.err" >nul 2>&1 && del "*.err" || ver >nul
    @dir /b /a-d "*.lnk" >nul 2>&1 && del "*.lnk" || ver >nul
    @dir /b /a-d "*.pch" >nul 2>&1 && del "*.pch" || ver >nul
    @dir /b /a-d "*.bak" >nul 2>&1 && del "*.bak" || ver >nul
    @dir /b /a-d "$(WWOBJ)\*.obj" >nul 2>&1 && del "$(WWOBJ)\*.obj" || ver >nul
    @dir /b /a-d "$(WWOBJ)\*.exe" >nul 2>&1 && del "$(WWOBJ)\*.exe" || ver >nul
    @dir /b /a-d "$(WWOBJ)\*.lib" >nul 2>&1 && del "$(WWOBJ)\*.lib" || ver >nul
    @dir /b /a-d "$(WWOBJ)\*.dll" >nul 2>&1 && del "$(WWOBJ)\*.dll" || ver >nul
    @dir /b /a-d "$(WWOBJ)\*.map" >nul 2>&1 && del "$(WWOBJ)\*.map" || ver >nul
    @dir /b /a-d "$(WWOBJ)\*.err" >nul 2>&1 && del "$(WWOBJ)\*.err" || ver >nul
    @dir /b /a-d "$(WWOBJ)\*.lnk" >nul 2>&1 && del "$(WWOBJ)\*.lnk" || ver >nul
    @dir /b /a-d "$(WWOBJ)\*.pch" >nul 2>&1 && del "$(WWOBJ)\*.pch" || ver >nul
    @dir /b /a-d "$(WWOBJ)\*.bak" >nul 2>&1 && del "$(WWOBJ)\*.bak" || ver >nul
	@dir /b /a-d "$(WWOBJ)\IPXPROT.OBJ" >nul 2>&1 && del "$(WWOBJ)\IPXPROT.OBJ" || ver >nul
	@dir /b /a-d "$(WWOBJ)\IPXREAL.OBJ" >nul 2>&1 && del "$(WWOBJ)\IPXREAL.OBJ" || ver >nul
	@dir /b /a-d "$(WWOBJ)\IPXREAL.EXE" >nul 2>&1 && del "$(WWOBJ)\IPXREAL.EXE" || ver >nul
	@dir /b /a-d "$(WWOBJ)\IPXREAL.MAP" >nul 2>&1 && del "$(WWOBJ)\IPXREAL.MAP" || ver >nul
	@dir /b /a-d "$(WWOBJ)\IPXREAL.IBN" >nul 2>&1 && del "$(WWOBJ)\IPXREAL.IBN" || ver >nul
    

#############################################################################
# Default target
!ifdef WIN32
all: RA95.EXE
!else
all: GAME.DAT
!endif


#############################################################################
# Builds the JSHELL.LIB file.
$(WWOBJ)\JSHELL.LIB: $(LIBFILES) $(WWOBJ)\JSHELL.LNK
	$(LIB) -c $^@ @$(WWOBJ)\JSHELL.LNK

$(WWOBJ)\JSHELL.LNK: makefile
	%create $^@
	for %index in ($(LIBFILES))  do %append $^@ -+ $(WWOBJ)\%index

#############################################################################
# Builds the TECH.LIB file.
$(WWOBJ)\TECH.LIB: $(TECHFILES) $(WWOBJ)\TECH.LNK
	$(LIB) -c $^@ @$(WWOBJ)\TECH.LNK

$(WWOBJ)\TECH.LNK: makefile
	%create $^@
	for %index in ($(TECHFILES))  do %append $^@ -+ $(WWOBJ)\%index

#############################################################################
# Builds the stub replacement program.
CWSTUB.OBJ: CWSTUB.C
	*wcc /i=$(%WATCOM)\h /dQUIET /dVMM /ms /zQ -fo$(WWOBJ)\$^. $<

CWSTUB.EXE: CWSTUB.OBJ
	*watcom\binw\wlink system dos file $(WWOBJ)\cwstub.obj name cwstub.exe option quiet library \wat\lib386\dos\clibs.lib, \wat\lib386\math87s.lib, \wat\lib386\dos\emu87.lib


#############################################################################
# Build the EXE
GAME.DAT: $(WWOBJ)\tech.lib $(WWOBJ)\jshell.lib $(OBJECTS) $(LINKFILE) $(TECHFILE)
	-Echo "dos.exe" linking phase.
        $(%WATCOM)\binw\wlink name $(WWRUN)\dos.exe @$(LINKFILE)
	-Echo Binding phase.
        -$(%WATCOM)\binw\wstrip -n -q $(WWRUN)\dos.exe $(WWRUN)\temp.tmp
	-$(%WATCOM)\4gwbind $(%WATCOM)\4gwpro.exe $(WWRUN)\temp.tmp $(WWRUN)\game.dat -vmon
# -copy $(WWRUN)\game.dat C:\westwood\redalert
# -copy $(WWRUN)\game.dat C:\westwood\ra
# -copy $(WWRUN)\dos.exe C:\westwood\redalert
#	-copy $(WWRUN)\game.dat ..\cd\install
	-Echo "game.dat" executable completed.

RA95.EXE: $(WWOBJ)\TECH.LIB $(WWOBJ)\JSHELL.LIB $(OBJECTS) $(LINKFILE) $(%MPEGLIB)\MPGDLL.LIB
	Echo "RA95.EXE" linking phase. [$(LANGUAGE)]
#         $(%LINKER)\nwlink name $(WWRUN)\$@ @$(LINKFILE)
# ajw - Steve Tall replaced wlink with nwlink. Watcom fix allows more debug symbols in exe, so allows debugging in WD.
#        $(%WATCOM)\binw\wlink name $(WWRUN)\$@ @$(LINKFILE)
        $(%LINKER)\nwlink name $(WWOBJ)\RA95.EXE @$(LINKFILE)
        $(%WATCOM)\binnt\WRC cc_icon "$(WWOBJ)\RA95.EXE
#        copy $(WWRUN)\ra95.exe C:\westwood\redalert
#        copy $(WWRUN)\ra95.exe C:\westwood\ra
        echo f | @xcopy "$(WWOBJ)\RA95.MAP" "$(WWRUN)\$(RUN_NAME).MAP" /Y /F /R
#        echo f | @xcopy "$(WWOBJ)\RA95.SYM" "$(WWRUN)\$(RUN_NAME).SYM" /Y /F /R
        echo f | @xcopy "$(WWOBJ)\RA95.EXE" "$(WWRUN)\$(RUN_NAME).EXE" /Y /F /R
	Echo "RA95.EXE" executable completed! [$(LANGUAGE)]


#############################################################################
# This creates the linker command file for the DOS version.
conquer.lnk : makefile
	%create $^@
	%append $^@ system dos4g
	%append $^@ option stack=128k
	%append $^@ option redefsok
	%append $^@ option quiet
    %append $^@ option map=$(WWOBJ)\CONQUER.MAP
    %append $^@ option symfile=$(WWOBJ)\CONQUER.SYM
	%append $^@ option eliminate
	%append $^@ option caseexact
	%append $^@ option art              # List artificial symbols in the map file.
	%append $^@ option showdead         # List symbols associated with dead code and functions in the map file.
	%append $^@ option statics          # List static symbols in the map file.
	%append $^@ option mang             # Mangled symbols in the map file.
	%append $^@ library $(WWOBJ)\jshell.lib
	%append $^@ library $(WWOBJ)\tech.lib
	for %index in ($(OBJECTS))  do %append $^@ file $(WWOBJ)\%index
	for %index in ($(PROJ_LIBS)) do %append $^@ library $(WWLIB)\lib\%index
	for %index in ($(VQ_LIBS)) do %append $^@ library ..\vq\lib\%index
	for %index in ($(GCL_LIBS)) do %append $^@ library $(%GCL510)\w10\%index
#	%append $^@ debug watcom all


#############################################################################
# This creates the linker command file for the Windows 95 version.
win95.lnk : makefile
	%create $^@
	%append $^@ system win95
	%append $^@ option redefsok
	%append $^@ option quiet
    %append $^@ option map=$(WWOBJ)\RA95.MAP
    %append $^@ option symfile=$(WWOBJ)\RA95.SYM
    %append $^@ option eliminate
	%append $^@ option caseexact
	%append $^@ option stack=128k
#	%append $^@ debug watcom all
	%append $^@ option art              # List artificial symbols in the map file.
	%append $^@ option showdead         # List symbols associated with dead code and functions in the map file.
	%append $^@ option statics          # List static symbols in the map file.
	%append $^@ option mang             # Mangled symbols in the map file.
	for %index in ($(OBJECTS))  do %append $^@ file $(WWOBJ)\%index
	%append $^@ library $(WWOBJ)\jshell.lib
	%append $^@ library $(WWOBJ)\tech.lib
	%append $^@ library $(WWLIB)\lib\win32lib.lib
	%append $^@ library $(WWVQ)\lib\vqa32wp.lib
	%append $^@ library $(WWVQ)\lib\vqm32wp.lib
    %append $^@ library $(%WWIPX)\ipx\wwipx32.lib
	%append $^@ library $(%DXSDK)\lib\dxguid.lib
	%append $^@ library $(%DXSDK)\lib\ddraw.lib
	%append $^@ library $(%DXSDK)\lib\dsound.lib
	%append $^@ library $(WWLIB)\lib\keyboard.lib
	%append $^@ library $(%MPEGLIB)\mpgdll.lib
	%append $^@ library $(%DXMEDIA)\lib\amstrmid.lib
	%append $^@ library $(%DXMEDIA)\lib\strmbasd.lib
#	%append $^@ library $(%WATCOM)\lib386\nt\uuid.lib
	%append $^@ library $(%UUIDLIB)\uuid.lib

#############################################################
# Update source and art to network.
update: pre .SYMBOLIC
	-copy i:\cd1\*.* f:\projects\c&c0\cd\win95\cd1 /s /u
	-copy i:\cd2\*.* f:\projects\c&c0\cd\win95\cd2 /s /u
#	-copy i:\cd1\*.* f:\projects\c&c0\cd\dos\cd1 /s /u
#	-copy i:\cd2\*.* f:\projects\c&c0\cd\dos\cd2 /s /u
	-copy ..\art\ingame\*.* f:\projects\c&c0\art\ingame /u /v /s
	-copy ..\audio\sfx\*.* f:\projects\c&c0\audio\ingame\sfx /u /v /s
	-copy *.* f:\projects\c&c0\code /v /s /u
	-copy ..\wwflat32\*.* f:\projects\c&c0\wwflat32 /v /s /u
	-copy ..\win32lib\*.* f:\projects\c&c0\win32lib /v /s /u
	-copy ..\vq\*.* f:\projects\c&c0\vq /v /s /u
	-copy ..\winvq\*.* f:\projects\c&c0\winvq /v /s /u

pre: .SYMBOLIC
	-copy f:\projects\c&c0\editor\english\*.exe i:\cd1\install /u
	-copy f:\projects\c&c0\editor\english\*.exe i:\cd2\install /u
	-copy f:\projects\c&c0\editor\english\edit.dat i:\cd1\install /u
	-copy f:\projects\c&c0\editor\english\edit.dat i:\cd2\install /u
	-copy $(WWRUN)\rules.ini ..\maps /u
	-copy $(WWRUN)\rules.ini f:\projects\c&c0\maps /u
	-watcom\binw\wstrip -n -q $(WWRUN)\ra95.exe $(WWRUN)\ra95.exe
	-copy $(WWRUN)\ra95.exe i:\cd1\install /u
	-copy $(WWRUN)\ra95.exe i:\cd2\install /u
	-copy $(WWRUN)\game.dat i:\cd1\install /u
	-copy $(WWRUN)\game.dat i:\cd2\install /u
	packlist SETUP.LST
	-copy setup.pkg i:\cd1\setup95 /u
 	-copy setup.pkg i:\cd2\setup95 /u
	-mkdir f:\projects\c&c0\playtest\%_DATE
	-copy $(WWRUN)\ra95.exe f:\projects\c&c0\playtest\%_DATE /u /v
	-copy $(WWRUN)\game.dat f:\projects\c&c0\playtest\%_DATE /u /v
	-copy *.map f:\projects\c&c0\playtest\%_DATE /u /v
	-copy *.cpp *.h f:\projects\c&c0\playtest\%_DATE /u /v


#############################################################################
# Explicit rules to build the master zip files (used by Codewrite merge).
BILL_R.ZIP: pkzip.dat .SYMBOLIC
	-del f:\projects\c&c0\bill_r.zip
	-pkzip -p -u -x@pkzip.dat f:\projects\c&c0\bill_r.zip *.* eng\conquer.txt

MARIA_L.ZIP: pkzip.dat .SYMBOLIC
	-del f:\projects\c&c0\maria_l.zip
	-pkzip -p -u -x@pkzip.dat f:\projects\c&c0\maria_l.zip *.* eng\conquer.txt

BARRY_G.ZIP: pkzip.dat .SYMBOLIC
	-del f:\projects\c&c0\barry_g.zip
	-pkzip -p -u -x@pkzip.dat f:\projects\c&c0\barry_g.zip *.* eng\conquer.txt

PHIL_G.ZIP: pkzip.dat .SYMBOLIC
	-del f:\projects\c&c0\phil_g.zip
	-pkzip -p -u -x@pkzip.dat f:\projects\c&c0\phil_g.zip *.* eng\conquer.txt

DAVID_D.ZIP: pkzip.dat .SYMBOLIC
	-del f:\projects\c&c0\david_d.zip
	-pkzip -p -u -x@pkzip.dat f:\projects\c&c0\david_d.zip *.* eng\conquer.txt

BILL_P.ZIP: pkzip.dat .SYMBOLIC
	-del f:\projects\c&c0\bill_p.zip
	-pkzip -p -u -x@pkzip.dat f:\projects\c&c0\bill_p.zip *.* eng\conquer.txt

STEVE_T.ZIP: pkzip.dat .SYMBOLIC
	-del f:\projects\c&c0\steve_t.zip
	-pkzip -p -u -x@pkzip.dat f:\projects\c&c0\steve_t.zip *.* eng\conquer.txt

VICTOR_G.ZIP: pkzip.dat .SYMBOLIC
	-del f:\projects\c&c0\victor_g.zip
	-pkzip -p -u -x@pkzip.dat f:\projects\c&c0\victor_g.zip *.* eng\conquer.txt

# Special "mega-zip" process.
JOE_B.ZIP: pkzip.dat .SYMBOLIC
	-pkzip -rp -u -xcps\*.* -x@pkzip.dat f:\projects\c&c0\joe_b.zip


#############################################################################
# Rebuilds the master zip control file. This is used by the zip process.
PKZIP.DAT: makefile .SYMBOLIC
	%create $^@
	%append $^@ *.000
	%append $^@ *.@@@
	%append $^@ *.bak
	%append $^@ *.bat
	%append $^@ *.cfg
	%append $^@ *.csm
	%append $^@ *.dat
	%append $^@ *.def
	%append $^@ *.doc
	%append $^@ *.dsw
	%append $^@ *.err
	%append $^@ *.ewp
	%append $^@ *.ext
	%append $^@ *.i
	%append $^@ *.ide
	%append $^@ *.lnk
	%append $^@ *.log
	%append $^@ *.lst
	%append $^@ *.mac
	%append $^@ *.map
	%append $^@ *.mbt
	%append $^@ *.mk
	%append $^@ *.mk1
	%append $^@ *.mrt
	%append $^@ *.obj
	%append $^@ *.obr
	%append $^@ *.out
	%append $^@ *.pch
	%append $^@ *.pfs
	%append $^@ *.pgp
	%append $^@ *.pif
	%append $^@ *.pjt
	%append $^@ *.prf
	%append $^@ *.pro
	%append $^@ *.ptg
	%append $^@ *.rc
	%append $^@ *.rep
	%append $^@ *.rpt
	%append $^@ *.rst
	%append $^@ *.sym
	%append $^@ *.tag
	%append $^@ *.td
	%append $^@ *.td
	%append $^@ *.tgt
	%append $^@ *.tmp
	%append $^@ *.tr
	%append $^@ *.tr
	%append $^@ *.txt
	%append $^@ *.vec
	%append $^@ *.wpj
	%append $^@ *.zip
	%append $^@ *.~*
	%append $^@ an_prefs
	%append $^@ state.rst


#--------------------------------------------------------------------------
# The IPX assembly object files are created in a special way:
# IPXREAL is the real-mode code that gets stuffed into memory by protected-
# mode code.  It's assembled, then converted into a big header file by
# the 'EBN' utility.
# IPXPROT is the protected-mode code that includes IPXREAL.IBN, and
# provides routines to let C++ read the code's address & size.
#--------------------------------------------------------------------------
$(WWOBJ)\IPXREAL.IBN: $(WWOBJ)\IPXREAL.OBJ
	echo.
	@echo *** ENTERED IBN RULE ***
	echo [IPXREAL.IBN] Creating RSP
	%create $(WWOBJ)\IPXREAL.RSP
	%append $(WWOBJ)\IPXREAL.RSP $(WWOBJ)\IPXREAL.OBJ, $(WWOBJ)\IPXREAL.EXE, $(WWOBJ)\IPXREAL.MAP
#	%append $(WWOBJ)\IPXREAL.RSP $(WWOBJ)\IPXREAL.EXE
#	%append $(WWOBJ)\IPXREAL.RSP $(WWOBJ)\IPXREAL.MAP
    type "$(WWOBJ)\IPXREAL.RSP"
	echo [IPXREAL.IBN] Linking...
	$(%MSDOS) $(TASM)\bin\tlink @"$(WWOBJ)\IPXREAL.RSP"
    @if not exist "$(WWOBJ)\IPXREAL.EXE" (echo ERROR: tlink did not produce IPXREAL.EXE & exit 1)
	echo [IPXREAL.IBN] Stripping...
	$(%MSDOS) $(TASM)\bin\tdstrip "$(WWOBJ)\IPXREAL.EXE"
	echo [IPXREAL.IBN] EBN...
	$(%MSDOS) $(%UTILS)\ebn "$(WWOBJ)\IPXREAL.EXE"
    @if not exist "$(WWOBJ)\IPXREAL.IBN" (echo ERROR: ebn did not produce IPXREAL.IBN & exit 1)

$(WWOBJ)\IPXREAL.OBJ: IPXREAL.ASM
	echo.
	echo Assembling $<
	$(%MSDOS) $(TASM)\bin\tasm /zn /la /ml /m2 "IPXREAL.ASM","$(WWOBJ)\IPXREAL.OBJ"
    @if not exist "$(WWOBJ)\IPXREAL.OBJ" (echo ERROR: tasm did not produce IPXREAL.OBJ & exit 1)

IPXPROT.OBJ: $(WWOBJ)\IPXREAL.IBN IPXPROT.ASM
	echo.
	echo Assembling $<
	$(%MSDOS) $(TASM)\bin\tasm $(ASM_CFG) /I"$(WWOBJ)" "IPXPROT.ASM","$(WWOBJ)\IPXPROT.OBJ"
#	copy $(WWOBJ)\ipxprot.obj d:obj /U


ipx.obj: ipx.cpp function.h
	echo.
	echo Compiling $[.
	*$(CC) $(CC_CFG) -zz -fo$(WWOBJ)\$^. $[*.cpp

ipxmgr.obj: ipxmgr.cpp function.h
	echo.
	echo Compiling $[.
	*$(CC) $(CC_CFG) -zz -fo$(WWOBJ)\$^. $[*.cpp

ipxconn.obj: ipxconn.cpp function.h
	echo.
	echo Compiling $[.
	*$(CC) $(CC_CFG) -zz -fo$(WWOBJ)\$^. $[*.cpp

ipx95.obj: ipx95.cpp function.h
	echo.
	echo Compiling $[.
	*$(CC) $(CC_CFG) -zz -fo$(WWOBJ)\$^. $[*.cpp

winstub.obj: winstub.cpp ipx95.h tcpip.h function.h
	echo.
	echo Compiling $[.
	*$(CC) $(CC_CFG) -zz -fo$(WWOBJ)\$^. $[*.cpp



#**************************** End of makefile ******************************
