#
#	Command & Conquer Red Alert(tm)
#	Copyright 2025 Electronic Arts Inc.
#
#	This program is free software: you can redistribute it and/or modify
#	it under the terms of the GNU General Public License as published by
#	the Free Software Foundation, either version 3 of the License, or
#	(at your option) any later version.
#
#	This program is distributed in the hope that it will be useful,
#	but WITHOUT ANY WARRANTY; without even the implied warranty of
#	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#	GNU General Public License for more details.
#
#	You should have received a copy of the GNU General Public License
#	along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

#****************************************************************************
#
#        C O N F I D E N T I A L --- W E S T W O O D   S T U D I O S
#
#----------------------------------------------------------------------------
#
# PROJECT
#     VQAPlay 32-bit library.
#
# FILE
#     makefile (Watcom C/C++ 10.0a)
#
# DESCRIPTION
#     Makefile for generating the 32-bit VQAPlay library.
#
# PROGRAMMER
#     Denzil E. Long, Jr.
# 
# DATE
#     February 10, 1995
#
# ENVIROMENT
#     PRJ    - Projects path.
#     PRJVCS - Version control archive path.
#     WATCOM - Watcom C installation path.
#
#****************************************************************************

#----------------------------------------------------------------------------
# VERIFY ENVIROMENT
#----------------------------------------------------------------------------

.SILENT
.OPTIMIZE
.ERASE

#----------------------------------------------------------------------------
# PROJECTS DEPENDENT MACROS
#----------------------------------------------------------------------------

PRJNAME = VQA32WP
PRJDIR  = $(%PRJ)\VQA32

OBJECTS = &
	CONFIG.OBJ &
	TASK.OBJ &
	LOADER.OBJ &
	DRAWER.OBJ &
	AUDIO.OBJ &
	MONODISP.OBJ &
	DSTREAM.OBJ &
	UNVQBUFF.OBJ &
	UNVQVESA.OBJ &
	VERTAG.OBJ &
	CAPTION.OBJ &
#	UNVQXMDE.OBJ

#----------------------------------------------------------------------------
# PATH MACROS
#----------------------------------------------------------------------------

PATH_C   = $(PRJDIR)\
PATH_CPP = $(PRJDIR)\
PATH_H   = $(PRJDIR)\
PATH_ASM = $(PRJDIR)\
PATH_I   = $(PRJDIR)\
PATH_OBJ = $(PRJDIR)\OBJ
PATH_LIB = $(%PRJ)\LIB
PATH_EXE = $(PRJDIR)\

#----------------------------------------------------------------------------
# IMPLICIT RULE EXTENSIONS AND PATHS
#----------------------------------------------------------------------------

.EXTENSIONS :
.EXTENSIONS : .exe .lib .obj .c .cpp .asm .h .i

.c : $(PATH_C)
.cpp : $(PATH_CPP)
.h : $(PATH_H)
.asm : $(PATH_ASM)
.i : $(PATH_I)
.obj : $(PATH_OBJ)
.lib : $(PATH_LIB)
.exe : $(PATH_EXE)

#----------------------------------------------------------------------------
# Tools/commands & configurations
#----------------------------------------------------------------------------

CC_CMD   = wcc386
CCP_CMD  = wpp386
ASM_CMD  = tasm32
LINK_CMD = wlink
LIB_CMD  = wlib

CC_OPTS  = -i$(%PRJ)\INCLUDE;$(%WATCOM)\H;$(%WATCOM)\H\NT -j -zp1 -5r -mf -oaeilrt -s -zq -d1
ASM_OPTS = /t /m /w+ /jJUMPS /ml /p /z /i$(%PRJ)\INCLUDE\VQM32 /dPHARLAP_TNT=0
LIB_OPTS = /b /c /q
LINK_CFG = $(PRJNAME).lnk

#----------------------------------------------------------------------------
# DEFAULT TARGET
#----------------------------------------------------------------------------

all : $(PRJNAME).lib .SYMBOLIC

#---------------------------------------------------------------------------
# CLEAN TARGET
#---------------------------------------------------------------------------
clean: .SYMBOLIC
	-if exist "*.obj" del /q *.obj
	-if exist "*.exe" del /q *.exe
	-if exist "*.lib" del /q *.lib
	-if exist "*.dll" del /q *.dll
	-if exist "*.map" del /q *.map
	-if exist "*.err" del /q *.err
	-if exist "*.lnk" del /q *.lnk
	-if exist "*.pch" del /q *.pch
	-if exist "*.bak" del /q *.bak
	-if exist "$(%PRJ)\LIB\VQA32WP.LIB" del /q "$(%PRJ)\LIB\VQA32WP.LIB"

$(PRJNAME).lib : $(OBJECTS) .SYMBOLIC

#----------------------------------------------------------------------------
# Ensure build directories exist before any compilation
#----------------------------------------------------------------------------
.BEFORE
	@if not exist "$(PATH_OBJ)" md "$(PATH_OBJ)" 2>nul
	@if not exist "$(PATH_LIB)" md "$(PATH_LIB)" 2>nul

#----------------------------------------------------------------------------
# IMPLICIT RULES
#----------------------------------------------------------------------------

.c.obj: .AUTODEPEND
	echo Compiling $<
	$(CC_CMD) $(CC_OPTS) -fo=$(PATH_OBJ)\$^. $<
	$(LIB_CMD) $(LIB_OPTS) $(PATH_LIB)\$(PRJNAME).LIB -+$(PATH_OBJ)\$]&

.cpp.obj: .AUTODEPEND
	echo Compiling $<
	$(CCP_CMD) $(CC_OPTS) -fo=$(PATH_OBJ)\$^. $<
	$(LIB_CMD) $(LIB_OPTS) $(PATH_LIB)\$(PRJNAME).LIB -+$(PATH_OBJ)\$]&

.asm.obj:
	echo Assembling $<
	$(ASM_CMD) $(ASM_OPTS) $<,$(PATH_OBJ)\$^.
	$(LIB_CMD) $(LIB_OPTS) $(PATH_LIB)\$(PRJNAME).LIB -+$(PATH_OBJ)\$]&

update: .SYMBOLIC
	@echo Updating 'VQAPlay32' header files in '$(%PRJ)\INCLUDE\VQA32'!
	@if not exist "$(%PRJ)\INCLUDE\VQA32\" md "$(%PRJ)\INCLUDE\VQA32\" 2>nul
	@dir /b /a-d "$(PRJDIR)\*.h" >nul 2>&1 && xcopy "$(PRJDIR)\*.h" "$(%PRJ)\INCLUDE\VQA32\" /Y /F /R /I
	@dir /b /a-d "$(PRJDIR)\*.i" >nul 2>&1 && xcopy "$(PRJDIR)\*.i" "$(%PRJ)\INCLUDE\VQA32\" /Y /F /R /I
